import Navigation from "../components/navigatgion"

export const metadata = {
  title: {
	  template: "%s | Next.js ",
	  default: "Loading..."
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        {children}</body>
    </html>
  )
}
