import "../styles/global.css"
import { Inter } from "next/font/google"

const inter = Inter({subsets: ["latin"]})

export const metadata = {
  title: {
	  template: "%s | Next.js ",
	  default: "Loading..."
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-800 text-white`}>
        {children}</body>
    </html>
  )
}
